name: Package and Release

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest] #[macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Build electron
        run: npm run dist
      - name: Release macos
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
        with:
          body_path: release-note.md
          files: |
            dist/ForKrew*.dmg
            dist/ForKrew*.zip
            dist/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release windows
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/ForKrew*.exe
            dist/ForKrew*.blockmap
            dist/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}